// QQ Agent 本地中文表情词库。
//
// 上游模板键保持不变；这里仅提供用户可见的中文命令别名与搜索词。
// 相同题材在 C1 中常有普通版、动图版和分类版，分类版会自动追加中文
// 后缀，避免一个中文别名无声地命中错误版本。

const ALIASES_BY_SLUG = {
  'afraid-to-ask-andy': ['不敢问问题', '怕被笑话'],
  'all-my-homies-hate': ['兄弟们都讨厌', '大家都讨厌'],
  'always-has-been': ['一直都是', '原来一直如此'],
  'american-chopper-argument': ['美式摩托争吵', '五格争吵'],
  'anakin-padme-4-panel': ['阿纳金帕德梅', '阿纳金四格'],
  'and-just-like-that': ['就这样', '突然就没了'],
  'anthony-adams-rubbing-hands': ['搓手期待', '安东尼搓手'],
  'aragorn-black-gate': ['为了佛罗多', '阿拉贡冲锋'],
  'atlas-holding-earth': ['阿特拉斯举地球', '扛起地球'],
  'avatar-guy': ['一切都变了', '降世神通回忆'],
  'batman-slapping-robin': ['蝙蝠侠打罗宾', '蝙蝠侠扇耳光'],
  'bell-curve': ['智商钟形曲线', '中间人曲线'],
  'ben-affleck-smoking': ['本阿弗莱克抽烟', '疲惫抽烟'],
  'bernie-once-again-asking': ['伯尼再次请求', '我再次请求'],
  'big-thumb-guy': ['大拇指男', '尴尬点赞'],
  'bike-fall': ['自行车插棍', '骑车摔倒'],
  'blinking-white-guy': ['白人眨眼', '一脸疑惑眨眼'],
  'both-buttons-pressed': ['两个都按', '两个按钮都要'],
  'bow-down': ['跪拜', '膜拜'],
  'buff-doge-vs-cheems': ['肌肉狗对比小黄狗', '以前和现在的狗'],
  'change-my-mind': ['改变我的想法', '欢迎反驳'],
  'charlie-conspiracy': ['阴谋论白板', '疯狂分析'],
  'chef-skinner-letter': ['厨师读信震惊', '斯金纳读信'],
  'clown-applying-makeup': ['小丑化妆', '逐渐变小丑'],
  'competition-opponent': ['比赛遇到对手', '我的对手竟然是'],
  'comrade-wake-up': ['同志醒醒', '该醒了'],
  'confused-monkey': ['困惑猴子', '猴子疑惑'],
  'confused-travolta': ['迷茫特拉沃尔塔', '到处找人'],
  'crab-rave': ['螃蟹蹦迪', '螃蟹狂欢'],
  'crazy-fans': ['疯狂粉丝', '粉丝发疯'],
  'dafoe-looking-up': ['达福抬头', '抬头顿悟'],
  'dam': ['大坝', '水坝'],
  'deal-with-it': ['接受现实', '就这样吧'],
  'disappearing-kid': ['小孩消失', '原地消失'],
  'disappointed-black-guy': ['黑人失望', '从期待到失望'],
  'disaster-girl': ['灾难女孩', '火灾女孩'],
  'distracted-boyfriend': ['分心男友', '移情别恋'],
  'doge': ['狗头', '神烦狗'],
  'dont-make-me-tap-the-sign': ['别逼我敲牌子', '规则提醒牌'],
  'do-whatever-you-want': ['为所欲为', '想干嘛就干嘛'],
  'dr-evil-air-quotes': ['邪恶博士引号手势', '阴阳怪气引号'],
  'drake': ['德雷克二选一', '这个不要那个要'],
  'drake-hotline-bling': ['德雷克二选一', '这个不要那个要'],
  'elmo-fire': ['艾摩火焰', '艾摩看世界燃烧'],
  'epic-handshake': ['史诗握手', '强强联合'],
  'evil-kermit': ['邪恶柯米特', '内心的邪恶声音'],
  'expanding-brain': ['脑洞升级', '逐渐聪明'],
  'feelings-of-power': ['力量来源', '什么让人充满力量'],
  'fan-club-support': ['粉丝团应援', '应援'],
  'first-time': ['第一次吗', '这才哪到哪'],
  'friendship-ended': ['友谊结束', '有了新朋友'],
  'gentlemen-it-is-with-great-pleasure': ['很高兴通知大家', '绅士喜报'],
  'grave-victory': ['坟头庆祝', '墓地胜利'],
  'grus-plan': ['格鲁的计划', '计划翻车'],
  'hello-human-resources': ['人力资源吗', '双标举报'],
  'hide-the-pain-harold': ['强颜欢笑', '痛苦哈罗德'],
  'homer-bush': ['荷马退进草丛', '默默退场'],
  'horse-drawing': ['画马', '马越画越敷衍'],
  'hysterical-arguments': ['激烈争论', '歇斯底里争论'],
  'i-dont-want-to-play-with-you-anymore': ['我不想和你玩了', '抛弃旧玩具'],
  'iceberg': ['冰山图', '冰山理论'],
  'illusion-of-free-choice': ['自由选择的幻觉', '其实没得选'],
  'inhaling-seagull': ['海鸥吸气怒吼', '蓄力大喊'],
  'inside-you-there-are-two-wolves': ['身体里有两只狼', '内心两只狼'],
  'is-this-a-pigeon': ['这是鸽子吗', '指鹿为马'],
  'jim-halpert-explains': ['吉姆解释', '吉姆得意解释'],
  'jordan-schlansky-staring': ['乔丹盯着看', '播客凝视'],
  'judgemental-volturi': ['沃尔图里审判', '一群人嫌弃'],
  'left-exit-12-off-ramp': ['高速急转弯', '突然拐向出口'],
  'leonardo-laugh': ['小李子笑', '莱昂纳多笑'],
  'linus-fuck': ['莱纳斯爆粗', '莱纳斯骂人'],
  'long-day-factory': ['工厂漫长一天', '下班累瘫'],
  'ma-huateng-think': ['马化腾思考', '小马哥思考'],
  'megamind-no-bitches': ['超能坏蛋探头', '没人要吗'],
  'meloni-slap-trump': ['梅洛尼扇特朗普', '掌掴特朗普'],
  'mind-blown': ['大脑爆炸', '震撼到爆炸'],
  'mocking-spongebob': ['海绵宝宝阴阳怪气', '嘲讽海绵宝宝'],
  'moe-throws-barney': ['莫把人扔出去', '扔出酒吧'],
  'monkey-puppet': ['猴子木偶偷瞄', '尴尬侧目'],
  'mother-ignoring-kid-drowning': ['妈妈忽视溺水小孩', '泳池溺水小孩'],
  'mother-ignoring-kid-drowning-in-a-pool': ['妈妈忽视溺水小孩', '泳池溺水小孩'],
  'mr-bean-waiting': ['憨豆等待', '等到不耐烦'],
  'none-of-my-business': ['不关我的事', '柯米特喝茶'],
  'obama-medal': ['奥巴马给自己颁奖', '自我表彰'],
  'ol-reliable': ['老可靠了', '可靠老办法'],
  'one-does-not-simply': ['哪有那么简单', '不能说做就做'],
  'oprah-you-get-a-car': ['人人有份', '奥普拉送车'],
  'oprah-you-get-a-car-gif': ['人人有份动图', '奥普拉送车动图'],
  'panik-kalm-panik': ['慌张冷静再慌张', '慌冷慌'],
  'peace-sign-tombstone': ['坟墓前比耶', '墓碑告别'],
  'rage-table-smash': ['愤怒砸桌', '掀桌动图'],
  'really-right-in-front-of-my': ['就在我面前吗', '当着我的面'],
  'red-pill-blue-pill': ['红蓝药丸', '二选一药丸'],
  'robotnik-button': ['蛋头博士按按钮', '按哪个按钮'],
  'roll-safe': ['指头点脑袋', '机智黑人'],
  'running-away-balloon': ['追气球', '被拦住的气球'],
  'sad-pablo-escobar': ['孤独毒枭', '巴勃罗等待'],
  'scooby-doo-mask-reveal': ['史酷比揭面具', '摘下面具'],
  'scroll-of-truth': ['真理卷轴', '拒绝真相'],
  'see-nobody-cares': ['没人在乎', '看吧没人关心'],
  'shrek-running': ['史莱克奔跑', '史莱克追赶'],
  'skinner-out-of-touch': ['是我落伍了吗', '校长拒绝反思'],
  'sleeping-shaq': ['奥尼尔睡醒', '奥尼尔选择'],
  'smiling-cat': ['礼貌猫', '微笑猫'],
  'something-of-a-scientist': ['我也算科学家', '绿魔科学家'],
  'soyboy-vs-yes-chad': ['弱男对比硬汉', '宅男和猛男'],
  'spongebob-ight-imma-head-out': ['海绵宝宝告辞', '我先走了'],
  'spongebob-looking-out-window': ['海绵宝宝望窗外', '羡慕地看窗外'],
  'squid-game': ['鱿鱼游戏', '鱿鱼游戏裁判'],
  'squidward-chair': ['章鱼哥坐椅子', '无聊章鱼哥'],
  'star-wars-yoda': ['星战尤达', '尤达大师'],
  'steve-buscemi-fellow-kids': ['年轻人你们好', '强行融入年轻人'],
  'straight-to-jail': ['直接进监狱', '统统坐牢'],
  'success-kid': ['成功小孩', '握拳小孩'],
  'sun-tzu': ['孙子兵法', '孙子说'],
  'support-tower': ['应援塔', '支持塔'],
  'surprised-pikachu': ['震惊皮卡丘', '意外吗皮卡丘'],
  'terminator-and-fear-girl': ['终结者与害怕女孩', '终结者追女孩'],
  'theyre-the-same-picture': ['这两张图一样', '根本是同一张图'],
  'thinking-about-other-women': ['他肯定在想别的女人', '床上各想各的'],
  'this-is-fine': ['问题不大', '一切都好'],
  'trade-offer': ['交易请求', '我得到你得到'],
  'truman-show': ['楚门的世界顿悟', '发现被监视'],
  'trump-bill-signing': ['特朗普签署法案', '特朗普举牌'],
  'trump-blank-executive-order': ['特朗普行政令', '特朗普空白举牌'],
  'tuxedo-winnie-the-pooh': ['西装维尼', '普通和高级'],
  'two-buttons': ['两个按钮', '左右为难'],
  'two-guys-on-a-bus': ['公交车两个人', '乐观与悲观'],
  'typing-cat': ['打字猫', '猫猫敲键盘'],
  'uncle-sam': ['山姆大叔需要你', '征召海报'],
  'undertaker-behind': ['送葬者背后出现', '背后偷袭'],
  'vince-mcmahon-glowing-eyes': ['文斯逐渐兴奋', '四段兴奋'],
  'wake-up-babe': ['宝贝快醒醒', '快起来看新闻'],
  'whisper-and-goosebumps': ['耳边低语起鸡皮疙瘩', '听完起鸡皮疙瘩'],
  'whisper-goosebumps': ['耳边低语起鸡皮疙瘩', '听完起鸡皮疙瘩'],
  'who-killed-hannibal': ['是谁杀了汉尼拔', '甩锅汉尼拔'],
  'woman-yelling-at-cat': ['女人吼猫', '吵架猫'],
  'x-x-everywhere': ['到处都是', '满眼都是'],
  'xbox-achievement': ['解锁成就', 'Xbox成就'],
  'yes-honey': ['好的亲爱的', '无奈答应'],
  'yhorm-dark-souls': ['黑魂巨人尤姆', '巨人尤姆'],

  // 动物、游戏、多格和职场分类中的高频模板。
  '100-men-vs-1-gorilla': ['一百人大战一只大猩猩'],
  'actual-advice-mallard': ['靠谱建议鸭'],
  'angry-doge': ['愤怒狗头'],
  'banana-cat': ['香蕉猫'],
  'business-cat': ['商务猫', '老板猫'],
  'capybara': ['卡皮巴拉', '水豚'],
  'cheems-bonk': ['小黄狗敲头', '狗头锤'],
  'cheems': ['小黄狗', '契姆斯'],
  'crying-cat': ['哭泣猫', '流泪猫猫'],
  'grumpy-cat': ['不爽猫', '暴躁猫'],
  'heavy-breathing-cat': ['猫猫急促呼吸', '兴奋猫'],
  'maxwell-cat': ['麦克斯韦猫', '旋转猫'],
  'moo-deng-side-eye': ['弹跳猪斜眼', '河马斜眼'],
  'peace-was-never-an-option': ['和平从来不是选项', '暴躁鹅'],
  'screaming-hamster': ['尖叫仓鼠'],
  'staring-hamster': ['凝视仓鼠', '视频通话仓鼠'],
  'swole-doge': ['肌肉狗头', '强壮狗头'],
  'trojan-horse': ['特洛伊木马'],
  'andy-dwyer-excited': ['安迪兴奋', '兴奋庆祝'],
  'bateman-walking': ['贝特曼走路', '西装男走路'],
  'coffin-dance': ['黑人抬棺', '抬棺舞'],
  'confused-math-lady': ['数学女士困惑', '满脑子公式'],
  'giga-chad-moving': ['超级猛男动图', '吉嘉猛男'],
  'happy-to-sad': ['从开心到难过'],
  'no-no-wait-wait': ['不不等等', '等一下别走'],
  'pedro-pascal-crying': ['佩德罗边哭边笑'],
  'sweating-jordan-peele': ['紧张流汗', '乔丹皮尔流汗'],
  'talking-to-wall': ['对墙说话', '白费口舌'],
  'this-is-sparta': ['这就是斯巴达', '斯巴达踢人'],
  'ancient-aliens': ['远古外星人', '都是外星人干的'],
  'arthur-fist': ['亚瑟握拳', '忍住怒气'],
  'bad-luck-brian': ['倒霉布莱恩', '倒霉蛋'],
  'brace-yourselves': ['做好准备', '凛冬将至'],
  'bugs-bunny-no': ['兔八哥拒绝', '不可以'],
  'captain-picard-facepalm': ['皮卡德捂脸', '舰长捂脸'],
  'futurama-fry': ['未来飞疑惑', '不确定是不是'],
  'hackerman': ['黑客大神', '黑客帝国大神'],
  'lisa-simpson-presentation': ['丽萨演讲', '辛普森演示板'],
  'math-lady': ['数学女士', '疯狂计算'],
  'modern-problems': ['现代问题需要现代方案'],
  'not-stonks': ['不是赚麻了', '亏麻了'],
  'pawn-stars-best-i-can-do': ['我最多只能出', '典当行砍价'],
  'press-f-to-pay-respects': ['按F致敬', 'F键致敬'],
  'pro-gamer-move': ['职业玩家操作', '高端操作'],
  'skyrim-finally-awake': ['你终于醒了', '老滚醒来'],
  'stonks': ['赚麻了', '股票上涨'],
  'task-failed-successfully': ['任务失败但成功了', '失败得很成功'],
  'the-cake-is-a-lie': ['蛋糕是谎言'],
  'who-is-that-pokemon': ['这是谁的宝可梦', '猜猜宝可梦'],
  'wild-pokemon-appears': ['野生宝可梦出现了'],
  'ambulance-not-for-me': ['叫救护车但不是给我', '反杀救护车'],
  'average-fan-vs-average-enjoyer': ['普通粉丝对比资深爱好者'],
  'boardroom-meeting-suggestion': ['会议室提建议', '老板扔员工'],
  'daily-struggle': ['每日艰难选择', '每天都在纠结'],
  'domino-effect': ['多米诺效应', '小事引发大事'],
  'hard-to-swallow-pills': ['难以下咽的药', '难以接受的真相'],
  'idiot-sandwich': ['笨蛋三明治'],
  'spiderman-pointing': ['蜘蛛侠互指', '两个蜘蛛侠'],
  'trolley-problem': ['电车难题'],
  'uno-draw-25': ['不做就摸二十五张', 'UNO摸二十五张'],
  'why-cant-you-just-be-normal': ['你为什么不能正常点'],
  'jackie-chan-confused': ['成龙困惑', '成龙一脸问号'],
  'disappointment-immeasurable': ['失望无法估量', '我的一天毁了'],
  'mom-come-pick-me-up': ['妈妈快来接我', '我害怕'],
  'third-place-celebration': ['第三名疯狂庆祝'],
  'you-guys-are-getting-paid': ['你们居然有工资', '原来你们有钱拿']
};

const PACK_PREFIXES = {
  animals: { suffix: '动物版', search: ['动物表情', '动物梗图'] },
  animated: { suffix: '动图版', search: ['动态表情', 'GIF表情'] },
  characters: { suffix: '角色版', search: ['人物角色', '影视角色'] },
  choices: { suffix: '选择版', search: ['选择题', '二选一'] },
  gaming: { suffix: '游戏版', search: ['游戏梗', '游戏表情'] },
  panels: { suffix: '多格版', search: ['多格漫画', '对比图'] },
  reactions: { suffix: '反应版', search: ['反应图', '情绪表情'] },
  work: { suffix: '职场版', search: ['职场梗', '程序员梗'] }
};

function splitPublicKey(publicKey) {
  const key = String(publicKey || '');
  if (key.startsWith('classic_')) return { source: 'classic', slug: key.slice('classic_'.length) };
  if (key.startsWith('gengtu_')) return { source: 'gengtu', slug: key.slice('gengtu_'.length) };
  return null;
}

export function chineseMemeTerms(publicKey) {
  const parsed = splitPublicKey(publicKey);
  if (!parsed) return { aliases: [], searchTerms: [] };

  let slug = parsed.slug;
  let pack = null;
  if (parsed.source === 'classic') {
    const prefix = Object.keys(PACK_PREFIXES).find((name) => slug.startsWith(`${name}-`));
    if (prefix) {
      pack = prefix;
      slug = slug.slice(prefix.length + 1);
    }
  }

  const baseAliases = ALIASES_BY_SLUG[slug] || [];
  const aliases = pack
    ? baseAliases.map((alias) => `${alias}${PACK_PREFIXES[pack].suffix}`)
    : [...baseAliases];
  const searchTerms = pack
    ? [...baseAliases, ...PACK_PREFIXES[pack].search]
    : [];
  return {
    aliases: [...new Set(aliases)],
    searchTerms: [...new Set(searchTerms)]
  };
}

export const chineseMemeAliasCount = Object.keys(ALIASES_BY_SLUG).length;
